#!/usr/bin/env bash

if [ -z "$SERVICES_LOCATION" ]; then
    SERVICES_LOCATION="$HOME/services"
fi

if [ -z "$RCLONE_REMOTE" ]; then
    RCLONE_REMOTE="backup"
fi

find-services () {
    target="$SERVICES_LOCATION"
    find "$target" -mindepth 1 -maxdepth 1 -type d
}

start-service () {
    service="$1"
    home="$SERVICES_LOCATION/$service"
    if ! [ -d "$home" ]; then
        echo "No such service: $service"
        return 1
    fi
    echo "Starting $service..."
    if [ -d "$home" ]; then
        pushd "$home" || return 1
        if [ -f "docker-compose.yml" ]; then
            docker compose up -d
        else # assume systemd
            systemctl start "$service.service"
        fi
        popd || return 1
    fi
}

stop-service () {
    service="$1"
    home="$SERVICES_LOCATION/$service"
    if ! [ -d "$home" ]; then
        echo "No such service: $service"
        return 1
    fi
    echo "Stopping $service..."
    if [ -d "$home" ]; then
        pushd "$home" || return 1
        if [ -f "docker-compose.yml" ]; then
            docker compose stop
        else # assume systemd
            systemctl stop "$service.service"
        fi
        popd || return 1
    fi
}

backup-service () {
    service="$1"
    home="$SERVICES_LOCATION/$service"
    if ! [ -d "$home" ]; then
        echo "No such service: $service"
        return 1
    fi
    echo "Backing up $service..."
    # today="$(date +%Y-%m-%d)"
    # rclone sync "$home" "$RCLONE_REMOTE:$service" --backup-dir "$RCLONE_REMOTE:$service-old/$today" --metadata
    rclone sync "$home" "$RCLONE_REMOTE:$service" --metadata
}

restore-service () {
    service="$1"
    home="$SERVICES_LOCATION/$service"
    if [ -d "$home" ]; then
        echo "Removing existing $service..."
        rm -rf "$home"
    fi
    mkdir -p "$home"
    echo "Restoring $service..."
    rclone copy "$RCLONE_REMOTE:$service" "$home" --metadata
}

clean-backups () {
    echo "Not implemented"
    return 0
    #service="$1"
    #backups="$BACKUPS_LOCATION/$service"
    #if ! [ -d "$backups" ]; then
    #    echo "No backups found for $service"
    #    return 1
    #fi
    #days="$2"
    #if [ -z "$days" ]; then
    #    echo "Provide minimum age in days to clean backups"
    #    return 1
    #fi
    #find "$backups" -type f -mtime "+$days" -exec rm {} \;
}

command="$1"
shift

case "$command" in
    start)
        if [ -n "$1" ]; then
            if ! start-service "$1"; then
                exit 1
            fi
        else
            services=$(find-services)
            for service in $services; do
                if ! start-service "$(basename "$service")"; then
                    exit 1
                fi
            done
        fi
        ;;
    stop)
        if [ -n "$1" ]; then
            if ! stop-service "$1"; then
                exit 1
            fi
        else
            services=$(find-services)
            for service in $services; do
                if ! stop-service "$(basename "$service")"; then
                    exit 1
                fi
            done
        fi
        ;;
    restart)
        if [ -n "$1" ]; then
            if ! stop-service "$1"; then
                exit 1
            fi
            if ! start-service "$1"; then
                exit 1
            fi
        else
            services=$(find-services)
            for service in $services; do
                if ! stop-service "$(basename "$service")"; then
                    exit 1
                fi
                if ! start-service "$(basename "$service")"; then
                    exit 1
                fi
            done
        fi
        ;;
    backup)
        if [ -n "$1" ]; then
            if ! stop-service "$1"; then
                exit 1
            fi
            if ! backup-service "$1"; then
                exit 1
            fi
            if ! start-service "$1"; then
                exit 1
            fi
        else
            services=$(find-services)
            for service in $services; do
                if ! stop-service "$(basename "$service")"; then
                    exit 1
                fi
                if ! backup-service "$(basename "$service")"; then
                    exit 1
                fi
                if ! start-service "$(basename "$service")"; then
                    exit 1
                fi
            done
        fi
        ;;
    restore)
        if [ -n "$1" ]; then
            stop-service "$1"
            if ! restore-service "$1"; then
                exit 1
            fi
        else
            echo -n "Confirm restoring all services (y/n) "
            read -r response
            if [ "$response" = "y" ]; then
                services=$(find-services)
                for service in $services; do
                    stop-service "$(basename "$service")"
                    if ! restore-service "$(basename "$service")"; then
                        exit 1
                    fi
                done
            fi
        fi
        ;;
    clean)
        if [ -z "$1" ]; then
            echo "Usage: $(basename "$0") clean [service] <days>"
            exit 1
        elif [ -n "$2" ]; then
            if ! clean-backups "$1" "$2"; then
                exit 1
            fi
        else
            services=$(find-services)
            for service in $services; do
                if ! clean-backups "$(basename "$service")" "$1"; then
                    exit 1
                fi
            done
        fi
        ;;
    *)
        echo "Usage: $(basename "$0") <start|stop|restart|backup|restore|clean> [service]"
        exit 1
        ;;
esac
