#!/usr/bin/env bash

hyprctl dispatch exec "[workspace 1 silent]" zen
hyprctl dispatch exec "[workspace 2 silent]" ghostty
hyprctl dispatch exec "[workspace 3 silent]" mysql-workbench
hyprctl dispatch exec "[workspace 4 silent]" postman
