#!/usr/bin/env bash

MY_ENV=${MY_ENV:-"$HOME/env"}
MY_OVERLAYS=${MY_OVERLAYS:-"$MY_ENV/environment/overlays"}

overlay_names="$(find "$MY_OVERLAYS" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)"

overlay="$(echo "$overlay_names" | head -c -1 | selector "Select overlay...")"

if [ -z "$overlay" ]; then
    echo "No overlay selected"
    exit 1
fi

OVERLAY="$overlay" dots switch
