#!/usr/bin/env bash

mode="dark"

while getopts ":w:m:c:" opt; do
    case "$opt" in
        w)
            wallpaper="$OPTARG"
            ;;
        m)
            mode="$OPTARG"
            if [ "$mode" != "dark" ] && [ "$mode" != "light" ]; then
                echo "Invalid mode: $mode"
                exit 1
            fi
            ;;
        c)
            colour="$OPTARG"
            ;;
        *)
            echo "Usage: $0 [-w <wallpaper>] [-m <mode>]"
            exit 1
            ;;
    esac
done

if [ -z "$wallpaper" ]; then
    if [ -z "$MY_ENV" ]; then
        MY_ENV="$HOME/env"
    fi

    if [ -z "$XDG_CONFIG_HOME" ]; then
        XDG_CONFIG_HOME="$HOME/.config"
    fi

    if [ -z "$MY_WALLPAPERS" ]; then
        MY_WALLPAPERS="$MY_ENV/wallpaper"
    fi

    wallpaper="$MY_WALLPAPERS/$(<"$XDG_CONFIG_HOME/theme/wallpaper")"
fi

if [ -z "$colour" ]; then
    colour=$(<"$XDG_CONFIG_HOME/theme/colour")
fi

if command -v matugen &> /dev/null; then
    if [ -n "$colour" ]; then
        matugen color hex "$colour" -m "$mode"
    elif [ -f "$wallpaper" ]; then
        matugen image "$wallpaper" -t "scheme-tonal-spot" -m "$mode" --source-color-index 0
    fi
fi
