#!/usr/bin/env bash

if [ -z "$MY_ENV" ]; then
    MY_ENV="$HOME/env"
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$MY_CONFIG" ]; then
    MY_CONFIG="$MY_ENV/environment/config"
fi

if [ -z "$SCRIPTS_HOME" ]; then
    SCRIPTS_HOME="$HOME/.local/scripts"
fi

if [ -z "$MY_SCRIPTS" ]; then
    MY_SCRIPTS="$MY_ENV/environment/scripts"
fi

if [ -z "$MY_HOSTS" ]; then
    MY_HOSTS="$MY_ENV/environment/hosts"
fi

if [ -z "$HOST" ]; then
    HOST=$(hostname)
fi

if [ -z "$MY_OVERLAYS" ]; then
    MY_OVERLAYS="$MY_ENV/environment/overlays"
fi

if [ -z "$OVERLAY" ]; then
    if [ -f "$MY_OVERLAYS/$HOST" ]; then
        OVERLAY=$(<"$MY_OVERLAYS/$HOST")
    else
        OVERLAY=$(<"$MY_OVERLAYS/current")
    fi
fi

move () {
    dir="$1"
    to="$2"
    rm -rf "$to"
    cp -R "$dir" "$to"
}

apply-overlay () {
    selection="$1"
    if [ ! -d "$selection" ]; then
        return 0
    fi
    find "$selection" -type f | while read -r file; do
        after=${file#"$selection/"}
        base=$(basename "$file")
        if [[ $base == "extension."* ]]; then
            newfile="$XDG_CONFIG_HOME/${after%"$base"}${base#"extension."}"
            cat "$file" >> "$newfile"
        else
            newfile="$XDG_CONFIG_HOME/$after"
            cp "$file" "$newfile"
        fi
    done
}

vicinae_running=$(pgrep vicinae)
noctalia_running=$(pgrep noctalia)

if [ -n "$vicinae_running" ]; then
    pkill vicinae
fi

if [ -n "$noctalia_running" ]; then
    kill -STOP "$noctalia_running"
fi

move "$MY_SCRIPTS" "$SCRIPTS_HOME"
chmod -R +x "$SCRIPTS_HOME"

find "$MY_CONFIG" -maxdepth 1 -mindepth 1 -type d | while read -r config; do
    base=$(basename "$config")
    move "$config" "$XDG_CONFIG_HOME/$base"
done

if [ -f "$XDG_CONFIG_HOME/session/default-session" ]; then
    chmod +x "$XDG_CONFIG_HOME/session/default-session"
fi
if [ -d "$XDG_CONFIG_HOME/session/scripts" ]; then
    chmod -R +x "$XDG_CONFIG_HOME/session/scripts"
fi

cp "$MY_CONFIG/zshrc" "$HOME/.zshrc"
cp "$MY_CONFIG/bashrc" "$HOME/.bashrc"

apply-overlay "$MY_HOSTS/$HOST"
apply-overlay "$MY_OVERLAYS/$OVERLAY"

if [ -n "$noctalia_running" ]; then
    kill -CONT "$noctalia_running"
fi

if [ -n "$vicinae_running" ]; then
    vicinae server &> /dev/null &
fi

"$SCRIPTS_HOME/set-theme"
