#!/usr/bin/env bash

# # To install, add to tmux.conf:
#
# # # Faster window switching:
# bind -n M-1 run-shell 'tmux-pin-pane sync ":1"; tmux select-window -t 1 || exit 0'
# bind -n M-2 run-shell 'tmux-pin-pane sync ":2"; tmux select-window -t 2 || exit 0'
# bind -n M-3 run-shell 'tmux-pin-pane sync ":3"; tmux select-window -t 3 || exit 0'
# bind -n M-4 run-shell 'tmux-pin-pane sync ":4"; tmux select-window -t 4 || exit 0'
# bind -n M-5 run-shell 'tmux-pin-pane sync ":5"; tmux select-window -t 5 || exit 0'
# bind -n M-6 run-shell 'tmux-pin-pane sync ":6"; tmux select-window -t 6 || exit 0'
# bind -n M-7 run-shell 'tmux-pin-pane sync ":7"; tmux select-window -t 7 || exit 0'
# bind -n M-8 run-shell 'tmux-pin-pane sync ":8"; tmux select-window -t 8 || exit 0'
# bind -n M-9 run-shell 'tmux-pin-pane sync ":9"; tmux select-window -t 9 || exit 0'
# bind -n M-0 run-shell 'tmux-pin-pane sync ":0"; tmux select-window -t 0 || exit 0'
#
# # # Keybindings:
# bind-key p run-shell -b "tmux-pin-pane toggle-pin"
# bind-key b run-shell -b "tmux-pin-pane toggle-display"
# bind-key B run-shell -b "tmux-pin-pane toggle-orientation"
#
# # # Sync state to tmux:
# set-hook -g session-window-changed 'run-shell -b "tmux-pin-pane sync"'
# set-hook -g pane-exited 'run-shell -b "tmux-pin-pane sync"'

command="$1"

if [ -z "$command" ] || ! { [ "$command" = "toggle-pin" ] || [ "$command" = "toggle-display" ] || [ "$command" = "toggle-orientation" ] || [ "$command" = "sync" ] ||  [ "$command" = "test" ]; }; then
    echo "Usage: $(basename "$0") <toggle-pin|toggle-display|toggle-orientation|sync|test> [sync target window]"
    exit 1
fi

if [ -z "$XDG_STATE_HOME" ]; then
    XDG_STATE_HOME="$HOME/.local/state"
fi

if [ -z "$COLLAPSE_WINDOW" ]; then
    COLLAPSE_WINDOW=":98"
fi

if [ -z "$DEFAULT_SIZE" ]; then
    DEFAULT_SIZE="30%"
fi

if [ -z "$DEFAULT_ORIENTATION" ]; then
    DEFAULT_ORIENTATION="vertical"
fi

if [ -z "$DEFAULT_DISPLAY" ]; then
    DEFAULT_DISPLAY="show"
fi

read_session_file() {
    session_file="$1"
    {
        read -r pin_pane
        read -r display
        read -r orientation
    } < "$session_file"
}

write_session_file() {
    session_file="$1"
    pin_pane="$2"
    display="$3"
    orientation="$4"

    echo -e "$pin_pane\n$display\n$orientation" > "$session_file"
}

sync_pane() {
    pin_pane="$1"
    display="$2"
    orientation="$3"
    target="$4"

    detach="-d"
    if [ "$display" = "show" ]; then
        if [ -z "$target" ]; then
            target="$window_id"
        fi
        if tmux has-session -t "$COLLAPSE_WINDOW"; then
            detach=""
        fi
    else
        if ! tmux has-session -t "$COLLAPSE_WINDOW"; then
            tmux neww -t "$COLLAPSE_WINDOW" -d
        fi
        target="$COLLAPSE_WINDOW"
    fi

    if [ "$orientation" = "vertical" ]; then
        target="$target.{bottom}"
    else
        target="$target.{left}"
    fi

    split="-v"
    if [ "$orientation" = "horizontal" ]; then
        split="-hb"
    fi

    target_pane_id=$(tmux display-message -t "$target" -p "#{pane_id}")
    if [ "$target_pane_id" = "$pin_pane" ]; then
        return 0
    fi

    if [ "$orientation" = "vertical" ]; then
        size=$(tmux display-message -t "$pin_pane" -p "#{pane_height}")
        max_size=$(tmux display-message -t "$target" -p "#{window_height}")
    else
        size=$(tmux display-message -t "$pin_pane" -p "#{pane_width}")
        max_size=$(tmux display-message -t "$target" -p "#{window_width}")
    fi
    if [ -z "$size" ] || [ "$size" -ge "$max_size" ] || [ "$size" -le 0 ]; then
        size="$DEFAULT_SIZE"
    fi

    if [ "$pin_pane" = "new" ]; then
        tmux split-window $split -t "$target" -l "$DEFAULT_SIZE"
    else
        tmux join-pane $detach $split -s "$pin_pane" -t "$target" -l "$size"
    fi

    if [ "$display" = "show" ] && tmux has-session -t "$COLLAPSE_WINDOW"; then
        tmux kill-pane -t "$COLLAPSE_WINDOW"
    fi
}

sync_pane_from_file() {
    session_file="$1"
    target="$2"
    if ! [ -f "$session_file" ]; then
        return 0
    fi
    read_session_file "$session_file"
    if ! tmux has-session -t "$pin_pane"; then
        rm "$session_file"
        return 0
    fi
    sync_pane "$pin_pane" "$display" "$orientation" "$target"
}

session=$(tmux display-message -p "#{session_name}")
pane_id=$(tmux display-message -p "#{pane_id}")
window_id=$(tmux display-message -p "#{window_id}")

if [ -z "$pane_id" ] || [ -z "$session" ] || [ -z "$window_id" ]; then
    exit 1
fi

session_file="$XDG_STATE_HOME/tmux-pin-pane/$session"

if ! [ -d "$XDG_STATE_HOME/tmux-pin-pane" ]; then
    mkdir -p "$XDG_STATE_HOME/tmux-pin-pane"
fi

if [ "$command" = "toggle-pin" ]; then
    if [ -f "$session_file" ]; then
        read -r pin_pane < "$session_file"
        if [ "$pane_id" = "$pin_pane" ]; then
            rm "$session_file"
            exit 0
        fi
    fi
    write_session_file "$session_file" "$pane_id" "$DEFAULT_DISPLAY" "$DEFAULT_ORIENTATION"
    sync_pane_from_file "$session_file"
elif [ "$command" = "sync" ]; then
    sync_pane_from_file "$session_file" "$2"
elif [ "$command" = "toggle-display" ]; then
    if ! [ -f "$session_file" ]; then
        sync_pane "new" "$DEFAULT_DISPLAY" "$DEFAULT_ORIENTATION" ""
        pane_id=$(tmux display-message -p "#{pane_id}")
        write_session_file "$session_file" "$pane_id" "$DEFAULT_DISPLAY" "$DEFAULT_ORIENTATION"
        exit 0
    fi
    read_session_file "$session_file"
    if [ "$display" = "show" ]; then
        display="hide"
    else
        display="show"
    fi
    write_session_file "$session_file" "$pin_pane" "$display" "$orientation"
    sync_pane_from_file "$session_file"
elif [ "$command" = "toggle-orientation" ]; then
    if ! [ -f "$session_file" ]; then
        exit 0
    fi
    read_session_file "$session_file"
    if [ "$orientation" = "vertical" ]; then
        orientation="horizontal"
    else
        orientation="vertical"
    fi
    write_session_file "$session_file" "$pin_pane" "$display" "$orientation"
    sync_pane_from_file "$session_file"
elif [ "$command" = "test" ]; then
    if [ -z "$TMUX" ] || [ ! -f "$session_file" ]; then
        exit 1
    fi
    read -r pin_pane < "$session_file"
    [ "$pin_pane" = "$pane_id" ]
fi
