#!/usr/bin/env bash

dirs=(
    "$HOME" "$HOME/work" "$HOME/programming"
    "$HOME/programming/js" "$HOME/programming/zig" "$HOME/programming/rust"
    "$HOME/programming/gleam" "$HOME/programming/golang" "$HOME/programming/elixir"
)
dir=$(find "${dirs[@]}" -maxdepth 1 -mindepth 1 -type d ! -path "*/.*" 2> /dev/null | fzf)
if [ -z "$dir" ]; then
    exit 1
fi

name=$(basename "$dir")

open () {
    if [ -n "$TMUX" ]; then
        tmux switch -t "$1" &> /dev/null
    else
        tmux attach -t "$1" &> /dev/null
    fi
}

pushd "$dir" > /dev/null
(git fetch &> /dev/null)&
popd > /dev/null

if tmux has-session -t "$name" &> /dev/null ; then
    open "$name"
    exit 0
fi

tmux new-session -c "$dir" -s "$name" -d
if [ -f "$dir/.session" ]; then
    tmux send-keys -t "$name" "source $dir/.session $name" c-M
elif [ -f "$HOME/nix/homeManager/scripts/.session" ]; then
    tmux send-keys -t "$name" "source $HOME/nix/homeManager/scripts/.session $name" c-M
fi

open "$name"
