#!/usr/bin/env bash

if [ -z "$SESSIONS_HOME" ]; then
    SESSIONS_HOME="$HOME/.local/sessions"
fi

dirs=(
    "$HOME" "$HOME/work" "$HOME/programming" "$HOME/programming/lua"
    "$HOME/programming/js" "$HOME/programming/zig" "$HOME/programming/rust"
    "$HOME/programming/gleam" "$HOME/programming/golang" "$HOME/programming/elixir"
)
dir=$(find "${dirs[@]}" -maxdepth 1 -mindepth 1 -type d ! -path "*/.*" 2> /dev/null | fzf)
if [ -z "$dir" ]; then
    exit 1
fi

name=$(basename "$dir")

open () {
    if [ -n "$TMUX" ]; then
        tmux switch -t "$1" &> /dev/null
    else
        tmux attach -t "$1" &> /dev/null
    fi
}

pushd "$dir" > /dev/null
(git fetch &> /dev/null)&
popd > /dev/null

if tmux has-session -t "$name" &> /dev/null ; then
    open "$name"
    exit 0
fi

tmux new-session -c "$dir" -s "$name" -d

if [ -f "$SESSIONS_HOME/$name/shell.fish" ]; then
    tmux set-option -t "$name" -s default-command "fish -C \"source $SESSIONS_HOME/$name/shell.fish $name\""
else 
    tmux set-option -t "$name" -s default-command "fish -C \"source $(which default-session-shell.fish) $name\""
fi

if [ -f "$SESSIONS_HOME/$name/session" ]; then
    tmux send-keys -t "$name" "$SESSIONS_HOME/$name/session $name" c-M
else
    tmux send-keys -t "$name" "default-session $name" c-M
fi

open "$name"
