#!/usr/bin/env bash

if [ -z "$SESSIONS_HOME" ]; then
    SESSIONS_HOME="$HOME/.local/sessions"
fi

if [ -z "$1" ]; then
    echo "Session directory required"
    exit 1
fi

dir="$1"

name=$(basename "$dir")

open () {
    if [ -n "$TMUX" ]; then
        tmux switch -t "$1" &> /dev/null
    else
        tmux attach -t "$1" &> /dev/null
    fi
}

pushd "$dir" > /dev/null
(git fetch &> /dev/null)&
popd > /dev/null

if tmux has-session -t "$name" &> /dev/null ; then
    open "$name"
    exit 0
fi

tmux new-session -c "$dir" -s "$name" -d

if [ -f "$SESSIONS_HOME/$name/shell.fish" ]; then
    tmux set-option -t "$name" -s default-command "fish -C \"source $SESSIONS_HOME/$name/shell.fish $name\""
fi

if [ -f "$SESSIONS_HOME/$name/session" ]; then
    tmux send-keys -t "$name" "$SESSIONS_HOME/$name/session $name" c-M
else
    tmux send-keys -t "$name" "default-session $name" c-M
fi

open "$name"
