#!/usr/bin/env bash

if [ -z "$HOST" ]; then
    HOST=$(hostname)
fi

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$MY_CONFIG" ]; then
    MY_CONFIG="$HOME/nix/homeManager/config"
fi

if [ -z "$MY_HOST_CONFIG" ]; then
    MY_HOST_CONFIG="$HOME/nix/homeManager/hostConfig/$HOST"
fi

if [ -z "$SCRIPTS_HOME" ]; then
    SCRIPTS_HOME="$HOME/.local/scripts"
fi

if [ -z "$MY_SCRIPTS" ]; then
    MY_SCRIPTS="$HOME/nix/homeManager/scripts"
fi

move () {
    dir="$1"
    to="$2"
    rm -rf "$to"
    cp -R "$dir" "$to"
}

append_host_to_config () {
    config="$XDG_CONFIG_HOME/$1"
    host="$MY_HOST_CONFIG/$1"
    cat "$host" >> "$config"
}

move_config () {
    move "$MY_CONFIG/$1" "$XDG_CONFIG_HOME/$1"
}

move "$MY_SCRIPTS" "$SCRIPTS_HOME"
chmod -R +x "$SCRIPTS_HOME"

move_config "ghostty"
move_config "tmux"
move_config "git"
move_config "btop"
move_config "waybar"
move_config "fuzzel"
move_config "yazi"
move_config "ulauncher"
move_config "nvim"
move_config "hypr"
append_host_to_config "hypr/hyprland.conf"

hyprctl reload
