#!/usr/bin/env bash

if [ -z "$MY_NIX" ]; then
    MY_NIX="$HOME/nix"
fi

current_generation=$(nixos-rebuild list-generations | grep current | awk '{print $1}')

sudo nixos-rebuild switch --flake "$MY_NIX"

# sudo nixos-rebuild switch --flake ~/nix

new_generation=$(nixos-rebuild list-generations | grep current | awk '{print $1}')

pushd "$MY_NIX" > /dev/null
if [ "$current_generation" != "$new_generation" ]; then
    git stage "*"
    git commit -m "$new_generation $1"
    echo "$new_generation: $1"
else
    echo "$new_generation: No Change"
fi
popd > /dev/null

switch-env
