[config]
import_json_files = [ "./values.json" ]

[config.wallpaper]
set = true
command = "pgrep noctalia && noctalia msg wallpaper-set {{ image }} 2> /dev/null"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty/matugen"
output_path = "~/.config/ghostty/matugen"
post_hook = "pgrep ghostty && systemctl reload --user app-com.mitchellh.ghostty.service"

[templates.noctalia]
input_path = "~/.config/matugen/templates/noctalia/noctalia.json"
output_path = "~/.config/noctalia/palettes/matugen.json"
post_hook = "pgrep noctalia && noctalia msg color-scheme-set custom matugen 2> /dev/null && noctalia msg theme-mode-set {{ mode }} 2> /dev/null"

[templates.gtk_0]
input_path = "~/.config/matugen/templates/gtk/gtk3.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk_1]
input_path = "~/.config/matugen/templates/gtk/gtk4.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.fuzzel_0]
input_path = "~/.config/matugen/templates/fuzzel/fuzzel.conf"
output_path = "~/.config/fuzzel/themes/matugen"

[templates.vicinae_0]
input_path = "~/.config/matugen/templates/vicinae/vicinae.toml"
output_path = "~/.local/share/vicinae/themes/matugen.toml"
post_hook = "pgrep vicinae && vicinae theme set matugen"

[templates.discord_midnight_vesktop]
input_path = "~/.config/matugen/templates/vesktop/midnight.css"
output_path = "~/.config/vesktop/themes/matugen.theme.css"

[templates.cava_0]
input_path = "~/.config/matugen/templates/cava/cava.ini"
output_path = "~/.config/cava/themes/matugen"

[templates.yazi_0]
input_path = "~/.config/matugen/templates/yazi/yazi.toml"
output_path = "~/.config/yazi/flavors/matugen.yazi/flavor.toml"

[templates.niri_0]
input_path = "~/.config/matugen/templates/niri/niri.kdl"
output_path = "~/.config/niri/matugen.kdl"
